name=input("enter you name:")
mobile_no=int(input("mobile no:"))
age=int(input("enter you age"))
gender=input("enter your gender")
degree=input("enter your degree")
city_name=input("enter you city")
cgpa=float(input("enter the cgpa:"))
course=input("enter you course:")
pursuing_course=bool(input("enter the boolean value"))
course_complete=bool(input("are you complete or not "))
print("im",name)
print("mobile no is :",mobile_no)
print("age is=",age)
print("gender",gender)
print("degree :",degree)
print(" i live in",city_name)
print("cgpa is:",cgpa)
print("course is",course)
print("pursuing",pursuing_course)
print("are you complete:",course_complete)
